issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('accounts/', include('accounts.urls')),
    path('webapp/', include('webapp.urls')),
]

webapp/urls.py
from django.urls import path
from webapp.views import ArticleListView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    CommentsCreateView, CommentsUpdateView, CommentsDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('article/add/', ArticleCreateView.as_view(), name='article_add'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/<int:pk>/comment/add/', CommentsCreateView.as_view(), name='comment_add'),
    path('comment/<int:pk>/update/', CommentsUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentsDeleteView.as_view(), name='comment_delete'),
]

webapp/models/article.py
from django.db import models
from django.urls import reverse

from webapp.models import BaseModel


class Article(BaseModel):
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name="Заголовок")
    author = models.CharField(max_length=50, null=False, blank=False, verbose_name="Автор")
    content = models.TextField(null=False, blank=False, verbose_name="Контент")
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', blank=True)

    def __str__(self):
        return f'{self.id}. {self.title}'

    class Meta:
        db_table = 'articles'
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk': self.pk})

webapp/models/base_model.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    class Meta:
        abstract = True

webapp/models/comment.py
from django.db import models

from webapp.models import BaseModel


class Comment(BaseModel):
    article = models.ForeignKey('webapp.Article', related_name='comments', on_delete=models.CASCADE,
                                verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.CharField(max_length=40, null=True, blank=True, default='Аноним', verbose_name='Автор')

    def __str__(self):
        return self.text[:20]

    class Meta:
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

webapp/models/tag.py
from django.db import models

from webapp.models import BaseModel


class Tag(BaseModel):
    name = models.CharField(max_length=31, verbose_name='Тег', unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tags'
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

webapp/forms/articles.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.forms import widgets

from webapp.models import Tag, Article


def at_least_5(string):
    if len(string) < 5:
        raise ValidationError('Поле не может быть короче 5 символов')


class ArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=50, required=True, validators=(at_least_5,), label="Название")

    class Meta:
        model = Article
        fields = ('title', 'author', 'content', 'tags')
        widgets = {
            'tags': widgets.CheckboxSelectMultiple()
        }

    def clean(self):
        title = self.cleaned_data.get('title')
        content = self.cleaned_data.get('content')
        if title and content and title == content:
            raise ValidationError('Заголовок и контент не могут быть равны')

        return super().clean()

webapp/forms/comments.py
from django import forms

from webapp.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text','author')

webapp/forms/search_form.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label="Найти")

webapp/views/articles.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import View, FormView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from webapp.forms import ArticleForm, SearchForm
from webapp.models import Article



class ArticleListView(ListView):
    model = Article
    template_name = 'articles/index.html'
    context_object_name = 'articles'
    ordering = ['-created_at']
    paginate_by = 3
    paginate_orphans = 2

    def dispatch(self, request, *args, **kwargs):
        # print(request.user)
        # print(request.user.is_authenticated)
        # print(request.user.is_anonymous)
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) | Q(author__icontains=self.search_value))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.search_form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search_value'] = self.search_value
        return context


class ArticleDetailView(DetailView):
    template_name = 'articles/article_view.html'
    model = Article
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.order_by('-created_at')
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'articles/article_create.html'
    form_class = ArticleForm
    # model = Article
    # fields = ['title', 'author', 'content', 'tags']

    # def get_success_url(self):
    #     return reverse('article_detail', kwargs={'pk': self.object.pk})
    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         return super().dispatch(request, *args, **kwargs)
    #     else:
    #         return redirect('accounts:login')


class ArticleUpdateView(UpdateView):
    template_name = 'articles/article_update.html'
    form_class = ArticleForm
    model = Article


class ArticleDeleteView(DeleteView):
    template_name = 'articles/article_delete.html'
    model = Article
    success_url = reverse_lazy('webapp:articles')

webapp/views/comments.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import CommentForm
from webapp.models import Comment, Article


class CommentsCreateView(CreateView):
    model = Comment
    template_name = 'comments/comment_create.html'
    form_class = CommentForm

    # def form_valid(self, form):
    #     article = get_object_or_404(Article, pk=self.kwargs['pk'])
    #     form.instance.article = article
    #     return super().form_valid(form)

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs['pk'])
        self.object = form.save(commit=False)
        self.object.article = article
        self.object.save()
        # form.save_m2m() Только если есть связь многие ко многим
        return redirect(article.get_absolute_url())

    # def get_success_url(self):
    #     return reverse('article_detail', kwargs={'pk': self.object.article.pk})

class CommentsUpdateView(UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'comments/comment_update.html'

    def get_success_url(self):
        return reverse('webapp:article_detail', kwargs={'pk': self.object.article.pk})


class CommentsDeleteView(DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect('webapp:article_detail', pk=self.object.article.pk)

webapp/templates/articles/article_create.html
{% extends "base.html" %}
{% block title %}Создание статьи{% endblock %}

{% block content %}
<h1>Создание Статьи</h1>

<form action="{% url 'webapp:article_add' %}" method="post">
    {% include 'partial/form.html' with button_text="Создать" %}
</form>
{% endblock %}

webapp/templates/articles/article_delete.html
{% extends 'base.html' %}

{% block title %}
	Удаление Статьи
{% endblock %}

{% block content %}
    <h1>Вы действительно хотите удалить статью "{{ article.title }}" ?</h1>
    <form method="post">
    {% csrf_token %}
        <input type="submit" value="Да">
    </form>
    <a href="{% url 'webapp:article_detail' article.id %}">Нет</a>
{% endblock %}

webapp/templates/articles/article_update.html
{% extends "base.html" %}
{% block title %}Изменение Статьи{% endblock %}

{% block content %}
<h1>Изменение Статьи "{{ article.title }}"</h1>

<form action="" method="post">
    {% include 'partial/form.html' with button_text="Изменить" %}
</form>
{% endblock %}

webapp/templates/articles/article_view.html
{% extends "base.html" %}
{% block title %}{{ article.title }}{% endblock %}

{% block menu %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:article_update' article.id %}">Изменить</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:article_delete' article.id %}">Удалить</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:comment_add'  article.id  %}">Добавить комментарий</a>
    </li>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            Автор: {{ article.author }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="card-text">{{ article.content }}</p>
            {% if article.tags.exists %}
                <p class="card-text">
                    Теги: {% for tag in article.tags.all %}{{ tag.name }}{% if forloop.last %}.{% else %},
                {% endif %} {% endfor %}
                </p>
            {% endif %}
        </div>
    </div>
    <h3 class="mt-3">Комментарии:</h3>
    <div class="row">
        {% for comment in comments %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Автор: {{ comment.author }}</h5>
                        <p class="card-text">{{ comment.text }}</p>
                        <a href="{% url "webapp:comment_update" comment.pk %}" class="btn btn-primary">Изменить</a>
                        <a href="{% url 'webapp:comment_delete' comment.pk %}" class="btn btn-primary">Удалить</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>Комментариев нет</p>
        {% endfor %}
    </div>
{% endblock %}

webapp/templates/articles/index.html
{% extends "base.html" %}
{% block title %}Статьи{% endblock %}
{% block menu %}
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:article_add' %}">Создать статью</a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Статьи</h1>
    <div class="my-2">
     {% include 'partial/search_form.html' with form=search_form %}
    </div>
    {% if is_paginated %}
        <div class="my-2">
        {% include 'partial/pagination.html' %}
        </div>
    {% endif %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for article in articles %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <p class="card-text">Автор: {{ article.author }}</p>
                        <a href="{% url "webapp:article_detail" article.pk %}" class="btn btn-primary">Подробнее</a>
                        <a href="{% url "webapp:article_update" article.pk %}" class="btn btn-primary">Изменить</a>
                        <a href="{% url "webapp:article_delete" article.pk %}" class="btn btn-primary">Удалить</a>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}